### ISSUE TITLE
Uncaught TypeError: editor.getBuffer(...).onDidChange is not a function

### ISSUE THREAD

**Issue by sanjorgek** [markushedvall/plantuml-preview#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [plantuml-viewer](https://github.com/markushedvall/plantuml-viewer) package 0.7.2

### Stack Trace

Uncaught TypeError: editor.getBuffer(...).onDidChange is not a function

```
At /Users/sanjorgek/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:78

TypeError: editor.getBuffer(...).onDidChange is not a function
    at PlantumlViewerView.attached (/packages/plantuml-viewer/lib/plantuml-viewer-view.js:78:42)
    at /packages/git-time-machine/node_modules/space-pen/lib/space-pen.js:164:63)
    at /packages/jslint/node_modules/space-pen/lib/space-pen.js:51:55)
    at atom-pane-container.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:135:24)
    at PaneContainer.deserialize (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:55:16)
    at WorkspaceCenter.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:30:30)
    at Workspace.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:416:42)
    at AtomEnvironment.module.exports.AtomEnvironment.deserialize (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1241:30)
    at AtomEnvironment.module.exports.AtomEnvironment.restoreStateIntoThisEnvironment (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1175:25)
    at atomDeserialize (/packages/recent-projects/node_modules/atom-project-util/index.js:86:17)
    at loadState.then (/packages/recent-projects/node_modules/atom-project-util/index.js:175:11)
```

### Commands

```
     -0:17.9.0 recent-projects:open (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -0:12.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
busy-signal 1.4.3 
circle-ci 0.10.1 
color-picker 2.2.5 
file-icons 2.1.9 
git-log 0.4.1 
git-time-machine 1.5.9 
goto-definition 1.3.4 
haskell-ghc-mod 1.19.9 
highlight-selected 0.13.1 
ide-haskell-cabal 1.9.2 
intentions 1.1.5 
jslint 1.5.1 
language-haskell 1.12.1 
language-restructuredtext 1.1.0 
language-sphinx 0.1.6 
linter 2.2.0 
linter-eslint 8.2.1 
linter-hlint 1.0.1 
linter-swagger 0.4.1 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-bookmarks 0.4.2 
minimap-git-diff 4.3.1 
node-repl 0.5.0 
npm-install 4.0.4 
npm-outdated 0.6.0 
open-html-in-browser 0.1.0 
pigments 0.39.1 
plantuml-viewer 0.7.2 
recent-projects 0.13.1 
rst-preview 1.3.1 
travis-ci-status 1.3.1 
zentabs 0.8.8 
```

**Comment by n1ywb** [comment]
FWIW I saw this come up after I upgraded Atom from 0.13 to 0.19. I had closed atom with a preview pane opened and the error appeared when I launched the new version of atom. closing and re-opening the preview pane seems to have worked around it as I am now getting the preview with no error.
